import {db,collection,getDocs,doc,updateDoc,addDoc,serverTimestamp} from "./firebase.js";
const producto=document.getElementById("producto"), productoResultado=document.getElementById("productoResultado"), stockActual=document.getElementById("stockActual"), cantidad=document.getElementById("cantidad"), cantidadObtenida=document.getElementById("cantidadObtenida"), pcn=document.getElementById("pcn"), pvn=document.getElementById("pvn"), observaciones=document.getElementById("observaciones"), boton=document.getElementById("guardarSalida"), tabla=document.getElementById("tablaTransformaciones");
let productos=[],movimientos=[],origen=null,resultado=null;
const norm=v=>String(v||"").trim().toUpperCase();
function fecha(m){try{const d=m.fecha?.toDate?m.fecha.toDate():new Date(m.fecha);return d.toLocaleDateString("es-ES")}catch(e){return ""}}
function actualizar(){origen=productos.find(p=>p.id===producto.value)||null;resultado=productos.find(p=>p.id===productoResultado.value)||null;stockActual.textContent=origen?Number(origen.stock||0):0}
function tablaHistorial(){const f=movimientos.filter(m=>m.tipo==="Transformación").sort((a,b)=>(b.fecha?.seconds||0)-(a.fecha?.seconds||0));tabla.innerHTML=f.length?f.map(m=>`<tr><td>${fecha(m)}</td><td><b>${m.pcn||""}</b></td><td><b>${m.pvn||""}</b></td><td>${m.productoOrigen||""}</td><td>${Number(m.cantidadUtilizada||0)}</td><td>${m.productoResultado||""}</td><td>${Number(m.cantidadObtenida||0)}</td><td>${m.observaciones||""}</td></tr>`).join(""):'<tr><td colspan="8">Todavía no hay transformaciones registradas.</td></tr>'}
async function cargar(){const[ps,ms]=await Promise.all([getDocs(collection(db,"productos")),getDocs(collection(db,"movimientos"))]);productos=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.nombre||"").localeCompare(String(b.nombre||"")));movimientos=ms.docs.map(d=>({id:d.id,...d.data()}));producto.innerHTML="";productoResultado.innerHTML='<option value="">Selecciona producto resultante</option>';for(const p of productos){producto.add(new Option(`${p.nombre} · Stock ${Number(p.stock||0)}`,p.id));productoResultado.add(new Option(`${p.nombre} · Stock ${Number(p.stock||0)}`,p.id))}actualizar();tablaHistorial()}
producto.onchange=actualizar;productoResultado.onchange=actualizar;
boton.onclick=async()=>{actualizar();const usada=Number(cantidad.value),obtenida=Number(cantidadObtenida.value),PCN=norm(pcn.value),PVN=norm(pvn.value);if(!origen)return alert("Selecciona producto de origen");if(!PCN)return alert("Introduce el PCN");if(!PVN)return alert("Introduce el PVN");if(!(usada>0))return alert("Introduce cantidad utilizada");if(usada>Number(origen.stock||0))return alert("No hay suficiente stock");if(!resultado)return alert("Selecciona producto resultante");if(origen.id===resultado.id)return alert("Origen y resultante deben ser distintos");if(!(obtenida>0))return alert("Introduce cantidad obtenida");if(!confirm(`Usar ${usada} de ${origen.nombre} y obtener ${obtenida} de ${resultado.nombre}. ¿Continuar?`))return;const oa=Number(origen.stock||0),ra=Number(resultado.stock||0);await updateDoc(doc(db,"productos",origen.id),{stock:oa-usada});await updateDoc(doc(db,"productos",resultado.id),{stock:ra+obtenida});await addDoc(collection(db,"movimientos"),{tipo:"Transformación",pcn:PCN,pvn:PVN,productoOrigenId:origen.id,productoOrigen:origen.nombre,codigoOrigen:origen.codigo||"",cantidadUtilizada:usada,stockOrigenAnterior:oa,stockOrigenFinal:oa-usada,productoResultadoId:resultado.id,productoResultado:resultado.nombre,codigoResultado:resultado.codigo||"",cantidadObtenida:obtenida,stockResultadoAnterior:ra,stockResultadoFinal:ra+obtenida,observaciones:observaciones.value.trim(),fecha:serverTimestamp()});alert("✅ Transformación registrada");location.reload()};
cargar();